export default [
	'Mozilla/5.0 (Windows NT 5.1; rv:11.0) Gecko Firefox/11.0 (via ggpht.com GoogleImageProxy)',
	'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)',
	'Mozilla/5.0 (compatible; Baiduspider/2.0; +http://www.baidu.com/search/spider.html)',
	'Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)',
	'Mozilla/5.0 (compatible; MJ12bot/v1.4.5; http://www.majestic12.co.uk/bot.php?+)',
	'Mozilla/5.0 (compatible; Yahoo! Slurp; http://help.yahoo.com/help/us/ysearch/slurp)',
	'Mozilla/5.0 (compatible; MegaIndex.ru/2.0; +http://megaindex.com/crawler)',
	'Mozilla/5.0 (compatible; AhrefsBot/5.2; +http://ahrefs.com/robot/)',
	'Mozilla/5.0 (X11; U; Linux Core i7-4980HQ; de; rv:32.0; compatible; JobboerseBot; http://www.jobboerse.com/bot.htm) Gecko/20100101 Firefox/38.0',
	'Mozilla/5.0 (compatible; DotBot/1.1; http://www.opensiteexplorer.org/dotbot, help@moz.com)',
	'Mozilla/5.0 (compatible; SemrushBot/2~bl; +http://www.semrush.com/bot.html)',
	'Mozilla/5.0 (compatible; YandexBot/3.0; +http://yandex.com/bots)',
	'Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.96 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)',
	'Mozilla/5.0 (compatible; MJ12bot/v1.4.7; http://mj12bot.com/)',
	'Mozilla/5.0 (compatible; MJ12bot/v1.4.8; http://mj12bot.com/)',
	'Mozilla/5.0 (compatible; SemrushBot/1.2~bl; +http://www.semrush.com/bot.html)',
	'Googlebot-Image/1.0',
	'Mozilla/5.0 (compatible; YandexImages/3.0; +http://yandex.com/bots)',
	'Mozilla/5.0 (compatible; Yahoo! Slurp/3.0; http://help.yahoo.com/help/us/ysearch/slurp)',
	'msnbot/1.0 (+http://search.msn.com/msnbot.htm)',
	'msnbot/2.0b (+http://search.msn.com/msnbot.htm)',
	'Mozilla/5.0 (compatible; AhrefsBot/5.0; +http://ahrefs.com/robot/)',
	'Mozilla/5.0 (compatible; seoscanners.net/1; +spider@seoscanners.net)',
	'Mozilla/5.0 (compatible; SEOkicks-Robot; +http://www.seokicks.de/robot.html)',
	'Mozilla/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11A465 Safari/9537.53 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)',
	'CheckMarkNetwork/1.0 (+http://www.checkmarknetwork.com/spider.html)',
	'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/534+ (KHTML, like Gecko) BingPreview/1.0b',
	'Mozilla/5.0 (compatible; AhrefsBot/5.1; +http://ahrefs.com/robot/)',
	'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36 Google (+https://developers.google.com/+/web/snippet/)',
	'facebookexternalhit/1.1 (+http://www.facebook.com/externalhit_uatext.php)',
	'Mozilla/5.0 (compatible; SemrushBot/1.1~bl; +http://www.semrush.com/bot.html)',
	'BUbiNG (+http://law.di.unimi.it/BUbiNG.html#wc)',
	'Mozilla/5.0 (X11; U; Linux Core i7-4980HQ; de; rv:32.0; compatible; JobboerseBot; https://www.jobboerse.com/bot.htm) Gecko/20100101 Firefox/38.0',
	'Mozilla/5.0 (compatible; AhrefsBot/6.1; +http://ahrefs.com/robot/)',
	'msnbot/1.1 (+http://search.msn.com/msnbot.htm)',
	'Mozilla/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11A465 Safari/9537.53 BingPreview/1.0b',
	'Baiduspider+(+http://www.baidu.com/search/spider.htm)',
	'Mozilla/5.0 (Windows; U; Windows NT 5.1; fr; rv:1.8.1) VoilaBot BETA 1.2 (support.voilabot@orange-ftgroup.com)',
	'Mozilla/5.0 (compatible; adscanner/)',
	'Mozilla/5.0 (compatible; Qwantify/2.4w; +https://www.qwant.com/)/2.4w',
	'Mozilla/5.0 (compatible; SISTRIX Crawler; http://crawler.sistrix.net/)',
	'Googlebot/2.1 (+http://www.google.com/bot.html)',
	'BUbiNG (+http://law.di.unimi.it/BUbiNG.html)',
	'DomainCrawler/3.0 (info@domaincrawler.com; http://www.domaincrawler.com/example.com)',
	'Mozilla/5.0 (compatible; Ask Jeeves/Teoma; +http://about.ask.com/en/docs/about/webmasters.shtml)',
	'msnbot-media/1.0 (+http://search.msn.com/msnbot.htm)',
	'Mozilla/5.0 (iPhone; U; CPU iPhone OS 4_1 like Mac OS X; en-us) AppleWebKit/532.9 (KHTML, like Gecko) Version/4.0.5 Mobile/8B117 Safari/6531.22.7 (compatible; Googlebot-Mobile/2.1; +http://www.google.com/bot.html)',
	'msnbot-media/1.1 (+http://search.msn.com/msnbot.htm)',
	'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.75 Safari/537.36 Google Favicon',
	'msnbot/0.01 (+http://search.msn.com/msnbot.htm)',
	'Screaming Frog SEO Spider/6.2',
	'Mozilla/5.0 (X11; U; Linux Core i7-4980HQ; de; rv:32.0; compatible; Jobboerse.com; http://www.xn--jobbrse-d1a.com) Gecko/20100401 Firefox/24.0',
	'Sogou web spider/4.0(+http://www.sogou.com/docs/help/webmasters.htm#07)',
	'Mozilla/5.0 (compatible; SEOkicks; +https://www.seokicks.de/robot.html)',
	'Mozilla/5.0 (compatible; DotBot/1.1; http://www.dotnetdotcom.org/, crawler@dotnetdotcom.org)',
	'Mozilla/2.0 (compatible; Ask Jeeves/Teoma)',
	'Mozilla/5.0 (compatible; ScoutJet; +http://www.scoutjet.com/)',
	'psbot/0.1 (+http://www.picsearch.com/bot.html)',
	'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; Googlebot/2.1; +http://www.google.com/bot.html) Safari/537.36',
	'Mozilla/5.0 (compatible; Exabot/3.0; +http://www.exabot.com/go/robot)',
	'Mozilla/2.0 (compatible; Ask Jeeves/Teoma; +http://sp.ask.com/docs/about/tech_crawling.html)',
	'Mozilla/5.0 (compatible; ExaleadCloudView/5;)',
	'Mozilla/5.0 (iPhone; CPU iPhone OS 8_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12F70 Safari/600.1.4 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)',
	'ZoominfoBot (zoominfobot at zoominfo dot com)',
	'Jyxobot/1',
	'msnbot/0.3 (+http://search.msn.com/msnbot.htm)',
	'Mozilla/5.0 (Windows; U; Windows NT 5.1; fr; rv:1.8.1) VoilaBot BETA 1.2 (http://www.voila.com/)',
	'Mozilla/4.0 (compatible; MSIE 5.0; Windows 95) VoilaBot BETA 1.2 (http://www.voila.com/)',
	'Mozilla/5.0 (iPhone; CPU iPhone OS 6_0 like Mac OS X) AppleWebKit/536.26 (KHTML, like Gecko) Version/6.0 Mobile/10A5376e Safari/8536.25 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)',
	'Mozilla/5.0 (compatible; MJ12bot/v1.4.3; http://www.majestic12.co.uk/bot.php?+)',
	'netEstate NE Crawler (+http://www.website-datenbank.de/)',
	'Mozilla/5.0 (compatible; 007ac9 Crawler; http://crawler.007ac9.net/)',
	'Mozilla/5.0 (compatible; TTD-Content; +https://www.thetradedesk.com/general/ttd-content)',
	'Mozilla/5.0 (compatible; YandexMetrika/2.0; +http://yandex.com/bots)',
	'Feedfetcher-Google; (+http://www.google.com/feedfetcher.html; 3 subscribers; feed-id=17583705103843181935)',
	'Mozilla/5.0 (compatible; DuckDuckGo-Favicons-Bot/1.0; +http://duckduckgo.com)',
	'Yahoo-MMCrawler/3.x (mms dash mmcrawler dash support at yahoo dash inc dot com)',
	'Mozilla/5.0 (compatible; YandexMetrika/2.0; +http://yandex.com/bots yabs01)',
	'ia_archiver',
	'Mozilla/5.0 (compatible; AhrefsBot/4.0; +http://ahrefs.com/robot/)',
	'Wotbox/2.01 (+http://www.wotbox.com/bot/)',
	'Mozilla/2.0 (compatible; Ask Jeeves/Teoma; +http://about.ask.com/en/docs/about/webmasters.shtml)',
	'FAST Enterprise Crawler 6 / Scirus scirus-crawler@fast.no; http://www.scirus.com/srsapp/contactus/',
	'Mozilla/5.0 (compatible; SiteExplorer/1.1b; +http://siteexplorer.info/Backlink-Checker-Spider/)',
	'Mozilla/5.0 (compatible; SemrushBot/3~bl; +http://www.semrush.com/bot.html)',
	'BacklinkCrawler (http://www.backlinktest.com/crawler.html)',
	'Pinterest/0.2 (+http://www.pinterest.com/)',
	'Mozilla/5.0 (compatible; MetaJobBot; http://www.metajob.de/crawler)',
	'AdsBot-Google (+http://www.google.com/adsbot.html)',
	'Mozilla/5.0 (compatible; Seekport Crawler; http://seekport.com/)',
	'Mozilla/5.0 (compatible; Konqueror/3.5; Linux) KHTML/3.5.5 (like Gecko) (Exabot-Thumbnails)',
	'Mozilla/5.0 (compatible; SemrushBot/0.98~bl; +http://www.semrush.com/bot.html)',
	'FAST MetaWeb Crawler (helpdesk at fastsearch dot com)',
	'msnbot/0.9 (+http://search.msn.com/msnbot.htm)',
	'Mozilla/5.0 (Twiceler-0.9 http://www.cuil.com/twiceler/robot.html)',
	'Mozilla/5.0 (compatible; SemrushBot/6~bl; +http://www.semrush.com/bot.html)',
	'msnbot/0.11 (+http://search.msn.com/msnbot.htm)',
	'Mozilla/5.0 (compatible; AhrefsSiteAudit/6.1; +http://ahrefs.com/robot/)',
	'Mozilla/5.0 (compatible; MegaIndex.ru/2.0; +https://www.megaindex.ru/?tab=linkAnalyze)',
	'Mozilla/5.0 (compatible; Pinterestbot/1.0; +http://www.pinterest.com/bot.html)',
	'CCBot/2.0 (http://commoncrawl.org/faq/)',
	'Linguee Bot (http://www.linguee.com/bot; bot@linguee.com)',
	'Mozilla/5.0 (compatible; SemrushBot/1~bl; +http://www.semrush.com/bot.html)',
	'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36; 360Spider',
	'Mozilla/5.0 (compatible; SemrushBot/1.0~bm; +http://www.semrush.com/bot.html)',
	'panscient.com',
	'Mozilla/5.0 (compatible; EasouSpider; +http://www.easou.com/search/spider.html)',
	'Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1 (compatible; AdsBot-Google-Mobile; +http://www.google.com/mobile/adsbot.html)',
	'AddThis.com (http://support.addthis.com/)',
	'Mozilla/5.0 (compatible; publiclibraryarchive.org/1.0; +crawl@publiclibraryarchive.org)',
	'Mozilla/5.0 (compatible; SiteExplorer/1.0b; +http://siteexplorer.info/)',
	'Mozilla/5.0 (compatible; Qwantify/2.2w; +https://www.qwant.com/)/*',
	'Mozilla/5.0 (compatible; AhrefsSiteAudit/6.1; +http://ahrefs.com/robot/site-audit)',
	'Mozilla/5.0 (X11; U; Linux Core i7-4980HQ; de; rv:32.0; compatible; JobboerseBot; https://www.jobboerse.com/bot.htm) Gecko/20100401 Firefox/24.0',
	'Mozilla/5.0 (compatible; SEOkicks-Robot; +https://www.seokicks.de/robot.html)',
	'SAMSUNG-SGH-E250/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 UP.Browser/6.2.3.3.c.1.101 (GUI) MMP/2.0 (compatible; Googlebot-Mobile/2.1; +http://www.google.com/bot.html)',
	'Mozilla/5.0 (compatible; YandexMetrika/2.0; +http://yandex.com/bots mtmon01e.yandex.ru)',
	'Barkrowler/0.7 (+http://www.exensa.com/crawl)',
	'Mozilla/5.0 (compatible; YandexMetrika/2.0; +http://yandex.com/bots mtmon01i.yandex.ru)',
	'Mozilla/5.0 (compatible; archive.org_bot +http://www.archive.org/details/archive.org_bot)',
	'Mediapartners-Google',
	'DoCoMo/2.0 N905i(c100;TB;W24H16) (compatible; Googlebot-Mobile/2.1; +http://www.google.com/bot.html)',
	'LCC (+http://corpora.informatik.uni-leipzig.de/crawler_faq.html)',
	'CCBot/2.0 (https://commoncrawl.org/faq/)',
	'Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0); 360Spider(compatible; HaosouSpider; http://www.haosou.com/help/help_3_2.html)',
	'BUbiNG (+http://law.di.unimi.it/BUbiNG.html#dc)',
	'AdsBot-Google ( http://www.google.com/adsbot.html)',
	'Mozilla/5.0 (compatible; Charlotte/1.1; http://www.searchme.com/support/)',
	'Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.92 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)',
	'Mozilla/5.0 (compatible; openstat.ru/Bot)',
	'Mozilla/5.0 (compatible; BecomeBot/3.0; +http://www.become.com/site_owners.html)',
	'Mozilla/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11A465 Safari/9537.53 (compatible; bingbot/2.0;  http://www.bing.com/bingbot.htm)',
	'Mozilla/5.0 (compatible; MJ12bot/v1.4.6; http://mj12bot.com/)',
	'Mozilla/5.0 (compatible; SemrushBot/0.99~bl; +http://www.semrush.com/bot.html)',
	'Mozilla/5.0 zgrab/0.x',
	'Mozilla/5.0 (compatible; YandexMetrika/2.0; +http://yandex.com/bots mtmon01g.yandex.ru)',
	'Mozilla/5.0 (compatible; Baiduspider/2.0; +http://www.baidu.com/search/spider.html	',
	'Riddler (http://riddler.io/about)',
	'Mozilla/5.0 (compatible;WI Job Roboter Spider Version 3;+https://www.webintegration.at)',
	'ichiro/3.0 (http://help.goo.ne.jp/door/crawler.html)',
	'Mozilla/5.0 (compatible; Yahoo! Slurp China; http://misc.yahoo.com.cn/help.html)',
	'G-i-g-a-b-o-t',
	'TurnitinBot (https://turnitin.com/robot/crawlerinfo.html)',
	'Aboundex/0.3 (http://www.aboundex.com/crawler/)',
	'Mozilla/5.0 (compatible; statdom.ru/Bot; +http://statdom.ru/bot.html)',
	'Slackbot-LinkExpanding 1.0 (+https://api.slack.com/robots)',
	'facebookexternalhit/1.1',
	'Mozilla/5.0 (compatible; special_archiver/3.1.1 +http://www.archive.org/details/archive.org_bot)',
	'Mozilla/5.0 (compatible; proximic; +https://www.comscore.com/Web-Crawler)',
	'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.1 (KHTML, like Gecko) Chrome/21.0.1180.89 Safari/537.1; 360Spider(compatible; HaosouSpider; http://www.haosou.com/help/help_3_2.html)',
	'ichiro/2.0 (http://help.goo.ne.jp/door/crawler.html)',
	'Twitterbot/1.0',
	'Mediatoolkitbot (complaints@mediatoolkit.com)',
	'Mozilla/5.0 (compatible; proximic; +http://www.proximic.com/info/spider.php)',
	'Mozilla/5.0 (compatible; GrapeshotCrawler/2.0; +http://www.grapeshot.co.uk/crawler.php)',
	'Mozilla/5.0 (compatible) Feedfetcher-Google; (+http://www.google.com/feedfetcher.html)',
	'noxtrumbot/1.0 (crawler@noxtrum.com)',
	'magpie-crawler/1.1 (U; Linux amd64; en-GB; +http://www.brandwatch.net)',
	'Mozilla/5.0 (X11; od-database-crawler) Gecko/20100101 Firefox/52.0',
	'VelenPublicWebCrawler (velen.io)',
	'Mozilla/5.0 (compatible; Daum/4.1; +http://cs.daum.net/faq/15/4118.html?faqId=28966)',
	'ia_archiver-web.archive.org',
	'Mozilla/5.0 (Windows; U; Windows NT 5.1; en; rv:1.9.0.13) Gecko/2009073022 Firefox/3.5.2 (.NET CLR 3.5.30729) SurveyBot/2.3 (DomainTools)',
	'Mozilla/5.0 (compatible; ca-crawler/1.0)',
	'Sosospider+(+http://help.soso.com/webspider.htm)',
	'Mozilla/5.0 (compatible; SemrushBot-SA/0.97; +http://www.semrush.com/bot.html)',
	'OFM search_robot .*google.*  (compatible; )',
	'Feedfetcher-Google; (+http://www.google.com/feedfetcher.html; 1 subscribers; feed-id=18446718903677612666)',
	'Mozilla/4.0 (compatible;  Vagabondo/4.0/EU; http://www.wise-guys.nl/)',
	'FAST-WebCrawler/3.8/Scirus (scirus-crawler@fast.no; http://www.scirus.com/srsapp/contactus/)',
	'Mozilla/5.0 (compatible; bnf.fr_bot; +http://www.bnf.fr/fr/outils/a.dl_web_capture_robot.html)',
	'Mozilla/5.0 (compatible; Baiduspider-render/2.0; +http://www.baidu.com/search/spider.html)',
	'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/601.2.4 (KHTML, like Gecko) Version/9.0.1 Safari/601.2.4 facebookexternalhit/1.1 Facebot Twitterbot/1.0',
	'Mozilla/5.0 (compatible; DeuSu/5.0.2; +https://deusu.de/robot.html)',
	'Mozilla/4.0 (compatible;  Vagabondo/4.0; http://www.wise-guys.nl/)',
	'Gigabot',
	'Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0); 360Spider',
	'Owlin - http://www.owlin.com',
	'Mozilla/5.0 (compatible; Dataprovider.com;)',
	'Mozilla/5.0 (compatible; Exabot/3.0 (BiggerBetter); +http://www.exabot.com/go/robot)',
	'Mozilla/5.0 (compatible; MJ12bot/v1.3.3; http://www.majestic12.co.uk/bot.php?+)',
	'Mozilla/5.0 (compatible; Qwantify/2.3w; +https://www.qwant.com/)/2.3w',
	'Mozilla/5.0 (Windows NT 6.1; rv:6.0) Gecko/20110814 Firefox/6.0 Google Favicon',
	'Mozilla/5.0 (Unknown; Linux x86_64) AppleWebKit/538.1 (KHTML, like Gecko) Safari/538.1 Daum/4.1',
	'Feedfetcher-Google; (+http://www.google.com/feedfetcher.html; 3 subscribers; feed-id=8106656927266266008)',
	'Mozilla/5.0 (compatible; YandexMetrika/2.0; +http://yandex.com/bots mtmon01f.yandex.ru)',
	'SEMrushBot',
	'Feedfetcher-Google; (+http://www.google.com/feedfetcher.html; 4 subscribers; feed-id=17583705103843181935)',
	'Pinterest/0.2 (+http://www.pinterest.com/bot.html)',
	'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; Google Web Preview Analytics) Chrome/41.0.2272.118 Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)',
	'ia_archiver (+http://www.alexa.com/site/help/webmasters; crawler@alexa.com)',
	'Feedfetcher-Google; (+http://www.google.com/feedfetcher.html; 1 subscribers; feed-id=7103972955513800065)',
	'Mozilla/5.0 (compatible; discobot/1.1; +http://discoveryengine.com/discobot.html',
	'Mozilla/5.0 (compatible; meanpathbot/1.0; +http://www.meanpath.com/meanpathbot.html)',
	'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; Google Web Preview Analytics) Chrome/27.0.1453 Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)',
	'ConveraCrawler/0.9d (+http://www.authoritativeweb.com/crawl)',
	'msnbot/2.0b (+http://search.msn.com/msnbot.htm)._',
	'Googlebot/2.1 (+http://www.googlebot.com/bot.html)',
	'Mozilla/5.0 (compatible; MJ12bot/v1.4.4; http://www.majestic12.co.uk/bot.php?+)',
	'Accoona-AI-Agent/1.1.2 (aicrawler at accoonabot dot com)',
	'Mozilla/5.0 (compatible; aiHitBot/2.9; +https://www.aihitdata.com/about)',
	'Mozilla/5.0 (compatible; heritrix/3.1.1; UniLeipzigASV +http://corpora.informatik.uni-leipzig.de/crawler_faq.html)',
	'Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1 (compatible; AdsBot-Google-Mobile;  http://www.google.com/mobile/adsbot.html)',
	'TurnitinBot/2.1 (http://www.turnitin.com/robot/crawlerinfo.html)',
	'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.1 (KHTML, like Gecko) Chrome/21.0.1180.89 Safari/537.1; 360Spider',
	'Baiduspider-image+(+http://www.baidu.com/search/spider.htm)',
	'Mozilla/5.0 (X11; od-database) Gecko/20100101 Firefox/52.0',
	'Mozilla/5.0 (compatible; Genieo/1.0 http://www.genieo.com/webfilter.html)',
	'Feedfetcher-Google; (+http://www.google.com/feedfetcher.html; 1 subscribers; feed-id=16616261776245151958)',
	'Feedfetcher-Google; (+http://www.google.com/feedfetcher.html; 1 subscribers; feed-id=5563361533657150793)',
	'Feedfetcher-Google; (+http://www.google.com/feedfetcher.html; 1 subscribers; feed-id=6744396557326865490)',
	'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.4.2661.102 Safari/537.36; 360Spider',
	'Feedfetcher-Google; (+http://www.google.com/feedfetcher.html; 1 subscribers; feed-id=4296914164355380091)',
	'Feedfetcher-Google; (+http://www.google.com/feedfetcher.html; 1 subscribers; feed-id=1425217532937691821)',
	'NaverBot-1.0 (NHN Corp. / +82-2-3011-1954 / nhnbot@naver.com)',
	'Mozilla/5.0 (compatible; BecomeBot/2.3; MSIE 6.0 compatible; +http://www.become.com/site_owners.html)',
	'Mozilla/5.0 (Windows NT 5.1; U; Win64; fr; rv:1.8.1) VoilaBot BETA 1.2 (support.voilabot@orange-ftgroup.com)',
	'Qwantify/1.0',
	'Barkrowler experimental crawler - 0.4.7',
	'Feedly/1.0 (+http://www.feedly.com/fetcher.html; like FeedFetcher-Google)',
	'Mozilla/5.0 (compatible; SEOkicks-Robot +http://www.seokicks.de/robot.html)',
	'OnPageBot (compatible; Googlebot 2.1; +https://bot.onpage.org/)',
	'CCBot/1.0 (+http://www.commoncrawl.org/bot.html)',
	'Mozilla/5.0 (compatible; Googlebot/2.1;  http://www.google.com/bot.html)',
	'Mozilla/5.0 (Twiceler-0.9 http://www.cuill.com/twiceler/robot.html)',
	'ConveraCrawler/0.9e (+http://www.authoritativeweb.com/crawl)',
	'Mozilla/5.0 (TweetmemeBot/4.0; +http://datasift.com/bot.html) Gecko/20100101 Firefox/31.0',
	'Mozilla/5.0 (compatible; 008/0.83; http://www.80legs.com/spider.html;) Gecko/2008032620',
	'Google favicon',
	'Mozilla/5.0 (compatible;WI Job Roboter Spider Version 3;+http://www.webintegration.at)',
	'Yeti/1.0 (NHN Corp.; http://help.naver.com/robots/)',
	'Mozilla/5.0 (compatible; MJ12bot/v1.2.1; http://www.majestic12.co.uk/bot.php?+)',
	'Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.92 Mobile Safari/537.36 (compatible; Googlebot/2.1;  http://www.google.com/bot.html)',
	'Gigabot/2.0/gigablast.com/spider.html',
	'Mozilla/5.0 (compatible; Baiduspider/2.0; +http://www.baidu.com/search/spider.html£©',
	'FAST Enterprise Crawler/6.4 (helpdesk at fast.no)',
	'Accoona-AI-Agent/1.1.1 (crawler at accoona dot com)',
	'Mozilla/5.0 zgrab/0.x (compatible; Researchscan/t13rl; +http://researchscan.comsys.rwth-aachen.de)',
	'Mozilla/5.0 (compatible; discobot/1.0; +http://discoveryengine.com/discobot.html)',
	'Gigabot/3.0 (http://www.gigablast.com/spider.html)',
	'Mozilla/5.0 (compatible; YodaoBot/1.0; http://www.yodao.com/help/webmaster/spider/; )',
	'facebookexternalhit/1.0 (+http://www.facebook.com/externalhit_uatext.php)',
	'Mozilla/5.0 (iPhone; CPU iPhone OS 6_0 like Mac OS X) AppleWebKit/536.26 (KHTML, like Gecko) Version/6.0 Mobile/10A5376e Safari/8536.25 (compatible; Googlebot-Mobile/2.1; +http://www.google.com/bot.html)',
	'ADmantX Platform Semantic Analyzer - ADmantX Inc. - www.admantx.com - support@admantx.com',
	'NerdyBot',
	'Mozilla/5.0 (compatible; Dataprovider.com)',
	'Mozilla/5.0 (compatible; YandexBot/3.0; +http://yandex.com/bots) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106',
	'MJ12bot/v1.0.7 (http://majestic12.co.uk/bot.php?+)',
	'Mozilla/4.0 (compatible; NaverBot/1.0; http://help.naver.com/customer_webtxt_02.jsp)',
	'Baiduspider+(+http://www.baidu.jp/spider/)'
]
